# Generated by Django 4.2.8 on 2025-03-28 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('MaBaiViet', models.AutoField(primary_key=True, serialize=False)),
                ('NoiDung', models.TextField()),
                ('ThoiGianDang', models.DateTimeField(default=django.utils.timezone.now)),
                ('SoLuongCamXuc', models.IntegerField(default=0)),
                ('TrangThai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DichVuCong',
            fields=[
                ('MaDV', models.AutoField(primary_key=True, serialize=False)),
                ('TenDichVu', models.CharField(max_length=255, verbose_name='Tên dịch vụ')),
            ],
        ),
        migrations.CreateModel(
            name='HoiThoai',
            fields=[
                ('MaHoiThoai', models.AutoField(primary_key=True, serialize=False)),
                ('TenHoiThoai', models.CharField(max_length=200)),
                ('ThoiGianTao', models.DateTimeField(auto_now_add=True)),
                ('LoaiHoiThoai', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('ma_nguoi_dung', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=255)),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10)),
                ('ngay_sinh', models.DateField()),
                ('ma_tai_khoan', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nhom',
            fields=[
                ('ma_nhom', models.AutoField(primary_key=True, serialize=False)),
                ('ten_nhom', models.CharField(max_length=255)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('so_luong_thanh_vien', models.IntegerField(default=0)),
                ('trang_thai_nhom', models.CharField(choices=[('Chờ duyệt', 'Chờ duyệt'), ('Được duyệt', 'Được duyệt'), ('Từ chối', 'Từ chối'), ('Bị xóa', 'Bị xóa')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('MaTaiKhoan', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('MatKhau', models.CharField(max_length=255)),
                ('DiemHDNK', models.IntegerField(default=0.0)),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_dung', to='social.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('MaTinNhan', models.AutoField(primary_key=True, serialize=False)),
                ('NoiDung', models.TextField()),
                ('ThoiGian', models.DateTimeField(auto_now_add=True)),
                ('MaHoiThoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan', to='social.hoithoai')),
                ('MaNguoiGui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_gui', to='social.taikhoan')),
            ],
        ),
        migrations.AddField(
            model_name='hoithoai',
            name='ThanhVien',
            field=models.ManyToManyField(related_name='hoi_thoai', to='social.taikhoan'),
        ),
        migrations.CreateModel(
            name='HoatDongNgoaiKhoa',
            fields=[
                ('ma_nk', models.AutoField(primary_key=True, serialize=False)),
                ('ten_hd_nk', models.CharField(help_text='Tên ngoại khóa.', max_length=255)),
                ('thoi_gian', models.DateTimeField(help_text='Thời gian diễn ra hoạt động.')),
                ('dia_diem', models.CharField(help_text='Địa điểm tổ chức hoạt động.', max_length=255)),
                ('mo_ta_hd_nk', models.TextField(blank=True, help_text='Mô tả chi tiết về hoạt động.', null=True)),
                ('so_luong', models.IntegerField(default=0, help_text='Số lượng người tham gia hoạt động.')),
                ('diem_hd_nk', models.FloatField(default=0, help_text='Điểm số của hoạt động ngoại khóa.')),
                ('muc_diem_nk', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], help_text='Mức điểm đạt được (I, II, III, IV).', max_length=3)),
                ('nguoi_dung', models.ForeignKey(help_text='Người tạo ngoại khoá.', on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='DKNgoaiKhoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_dk', models.DateTimeField(auto_now_add=True, help_text='Thời gian sinh viên đăng ký hoạt động.')),
                ('trang_thai', models.CharField(choices=[('DA_THAM_GIA', 'Đã tham gia'), ('KHONG_THAM_GIA', 'Không tham gia')], help_text='Trạng thái đăng ký hoạt động.', max_length=20)),
                ('ma_hd_nk', models.ForeignKey(help_text='Mã hoạt động ngoại khóa.', on_delete=django.db.models.deletion.CASCADE, to='social.hoatdongngoaikhoa')),
                ('ma_sv', models.ForeignKey(help_text='Mã sinh viên đăng ký hoạt động.', on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='DatLich',
            fields=[
                ('MaDatLich', models.AutoField(primary_key=True, serialize=False)),
                ('NgayDatLich', models.DateField(verbose_name='Ngày đặt lịch')),
                ('GioDatLich', models.TimeField(verbose_name='Giờ đặt lịch')),
                ('TrangThai', models.CharField(choices=[('Đã duyệt', 'Đã duyệt'), ('Từ chối', 'Từ chối')], max_length=20, verbose_name='Trạng thái')),
                ('MaDV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.dichvucong', verbose_name='Mã dịch vụ')),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mã người dùng')),
            ],
        ),
        migrations.CreateModel(
            name='CamXuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoaiCamXuc', models.CharField(max_length=50)),
                ('ThoiGian', models.DateTimeField(default=django.utils.timezone.now)),
                ('MaBaiViet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cam_xuc', to='social.baiviet')),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cam_xuc', to='social.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('MaBinhLuan', models.AutoField(primary_key=True, serialize=False)),
                ('NoiDung', models.TextField()),
                ('ThoiGianDang', models.DateTimeField(default=django.utils.timezone.now)),
                ('MaBaiViet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan', to='social.baiviet')),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan', to='social.nguoidung')),
            ],
        ),
        migrations.AddField(
            model_name='baiviet',
            name='MaNguoiDung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_viet', to='social.nguoidung'),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='MaNhom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_viet', to='social.nhom'),
        ),
        migrations.CreateModel(
            name='ThanhVienNhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vai_tro', models.CharField(choices=[('Quản trị viên', 'Quản trị viên'), ('Thành viên', 'Thành viên')], max_length=50)),
                ('thoi_gian_tham_gia', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('Chờ duyệt', 'Chờ duyệt'), ('Được duyệt', 'Được duyệt'), ('Từ chối', 'Từ chối'), ('Bị xóa', 'Bị xóa')], max_length=10)),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nguoidung')),
                ('ma_nhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.nhom')),
            ],
            options={
                'unique_together': {('ma_nhom', 'ma_nguoi_dung')},
            },
        ),
        migrations.AddConstraint(
            model_name='dkngoaikhoa',
            constraint=models.UniqueConstraint(fields=('ma_hd_nk', 'ma_sv'), name='unique_dk_hoatdong'),
        ),
        migrations.AlterUniqueTogether(
            name='camxuc',
            unique_together={('MaBaiViet', 'MaNguoiDung')},
        ),
    ]
